#!/usr/bin/env bash

read -r cpu user nice system idle iowait irq softirq steal guest guest_nice </proc/stat

prev_idle=$((idle + iowait))
prev_total=$((user + nice + system + idle + iowait + irq + softirq + steal))

sleep 0.2

read -r cpu user nice system idle iowait irq softirq steal guest guest_nice </proc/stat

idle_now=$((idle + iowait))
total_now=$((user + nice + system + idle + iowait + irq + softirq + steal))

total_diff=$((total_now - prev_total))
idle_diff=$((idle_now - prev_idle))

if [ "$total_diff" -eq 0 ]; then
  usage=0
else
  usage=$((100 * (total_diff - idle_diff) / total_diff))
fi

if [ "$usage" -ge 90 ]; then
  echo "󰻠 ${usage}%!"
  echo
  echo "#ff5555"
elif [ "$usage" -ge 70]; then
  echo "󰻠 ${usage}%"
  echo
  echo "#ffb86c"
else
  echo "󰻠 ${usage}%"
  echo
  echo "#bd93f9"
fi
