add_newline = false

format = """
${custom.os_icon}$directory${custom.git_provider}$git_branch$git_status$cmd_duration
$character"""

right_format = "$time"

palette = "void"

[palettes.void]
void_bg = "#0B0E14"
muted = "#9AA5CE"   #6C7086
path = "#A6D1FF"
violet = "#B48EFA"
gold = "#E6C384"
teal = "#7DCFFF"
green = "#9ECE6A"
red = "#F7768E"
orange = "#FF9E64"

[custom.os_icon]
description = "Show a quiet OS icon"
shell = ["bash", "--noprofile", "--norc"]
when = true
command = '''
case "$(uname -s)" in
  Darwin)
    printf " "
    ;;
  Linux)
    if [ -r /etc/os-release ]; then
      . /etc/os-release
      case "${ID:-}" in
        cachyos) printf " " ;;
        arch)    printf " " ;;
        fedora)  printf " " ;;
        ubuntu)  printf " " ;;
        debian)  printf " " ;;
        nixos)   printf " " ;;
        *)       printf " " ;;
      esac
    else
      printf " "
    fi
    ;;
  *)
    printf " "
    ;;
esac
'''
format = "[$output]($style)"
style = "muted"

[directory]
format = " [$path]($style) "
style = "path"
truncation_length = 4
truncate_to_repo = false
read_only = " ro"

[custom.git_provider]
description = "Show Git provider icon based on origin remote"
shell = ["bash", "--noprofile", "--norc"]
# when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
when = true
require_repo = true
command = '''
url="$(git config --get remote.origin.url 2>/dev/null || true)"

case "$url" in
  *github.com*) printf " " ;;
  *gitlab*|*foundry*)     printf " " ;;
  *bitbucket*)  printf " " ;;
  *azure.com*|*visualstudio.com*) printf "󰠅 " ;;
  "")           printf " " ;;
  *)            printf " " ;;
esac
'''
format = "[∷ $output]($style) "
style = "muted"

[git_branch]
format = " [$branch]($style) "
style = "gold"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "muted"
conflicted = "[!$count](red) "
ahead = "[↑$count](teal) "
behind = "[↓$count](orange) "
diverged = "[↑$ahead_count↓$behind_count](orange) "
untracked = "[?$count](muted) "
stashed = "[$$count](violet) "
modified = "[~$count](orange) "
staged = "[+$count](green) "
renamed = "[»$count](teal) "
deleted = "[-$count](red) "

[cmd_duration]
min_time = 2000
format = "[⧖ $duration]($style) "
style = "teal"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
style = "muted"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](violet)"
